<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ProductosApiNet8-Local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!-- Comparto el modelo y el ORM sin compilar los otros ejecutables dentro de esta aplicación. -->
    <Compile Remove="Productos.Core/**/*.cs;Productos.Grpc/**/*.cs;Pruebas/**/*.cs;Data/**/*.cs;DTOs/**/*.cs;Models/**/*.cs;Services/**/*.cs" />
    <Content Remove="Productos.Core/**;Productos.Grpc/**;Pruebas/**" />
    <None Remove="Productos.Core/**;Productos.Grpc/**;Pruebas/**" />
    <ProjectReference Include="Productos.Core/Productos.Core.csproj" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
