<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.67.0" PrivateAssets="All" />
    <PackageReference Include="Google.Protobuf" Version="3.28.2" />
    <Protobuf Include="../Productos.Grpc/Protos/productos.proto" GrpcServices="Client" Link="productos.proto" />
  </ItemGroup>
</Project>
